version: '2'

services:

  app:
    build:
      context: ./build/app
      dockerfile: ${app_dockerfile}
      args:
        - LOG_ERROR=${log_error}
        - LOG_ACCESS=${log_access}
        - MEMORY_LIMIT=${memory_limit}
        - POST_MAXSIZE=${post_maxsize}
        - UPLOAD_MAX_FILESIZE=${upload_max_filesize}
        - DATE_TIMEZONE=${date_timezone}
    ports:
      - 9000
      - 8081
    volumes:
      - ./data/passbolt/:/var/www/passbolt
    depends_on:
      - db
    environment:
      - ADMIN_EMAIL=${admin_email}
      - ADMIN_FIRSTNAME=${admin_firstname}
      - ADMIN_LASTNAME=${admin_lastname}
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${mysql_database}
      - MYSQL_USERNAME=${mysql_user}
      - MYSQL_PASSWORD=${mysql_password}
      - HOST_NAME=${proxy_domain}
      - APP_EMAIL_TRANSPORT=${app_email_transport}
      - APP_EMAIL_FROM_ADDRESS=${app_email_from_address}
      - APP_EMAIL_FROM_NAME=${app_email_from_name}
      - APP_EMAIL_HOST=${app_email_host}
      - APP_EMAIL_PORT=${app_email_port}
      - APP_EMAIL_TIMEOUT=${app_email_timeout}
      - APP_EMAIL_USERNAME=${app_email_username}
      - APP_EMAIL_PASSWORD=${app_email_password}
      - APP_EMAIL_USE_TLS=${app_email_use_tls}

  db:
    image: mysql:5.7.16
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${mysql_root_password}
      - MYSQL_DATABASE=${mysql_database}
      - MYSQL_USER=${mysql_user}
      - MYSQL_PASSWORD=${mysql_password}
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"]

  proxy:
    build: ./build/proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes_from:
      - app
    volumes:
      - ./config/app/app.conf:/etc/nginx/nginx.conf.template
      - ./data/web/lets-etc/:/etc/letsencrypt/
      - ./data/web/lets-var-lib/:/var/lib/letsencrypt/
      - ./data/web/nginx-root/:/usr/share/nginx/html/
    environment:
      - VIRTUAL_HOST=${proxy_domain}
      - ADMIN_EMAIL=${admin_email}
      - DOMAIN=${proxy_domain}
